CC ?= cc
SANITIZER_CC ?= clang
LUA ?= lua
PKG_CONFIG ?= pkg-config

LUA_PKG ?= lua5.4
LUA_CFLAGS := $(shell $(PKG_CONFIG) --cflags $(LUA_PKG) 2>/dev/null || $(PKG_CONFIG) --cflags lua 2>/dev/null)
LUA_LIBS := $(shell $(PKG_CONFIG) --libs $(LUA_PKG) 2>/dev/null || $(PKG_CONFIG) --libs lua 2>/dev/null)

# app_support.c pulls in GTK for the shared path chooser; the tests link it
# but never open a dialog. glib-2.0 covers the pure layers (json_io, pdf_toc,
# workspace_store) that need strings and files but no toolkit.
GTK_CFLAGS := $(shell $(PKG_CONFIG) --cflags gtk+-3.0 2>/dev/null)
GLIB_CFLAGS := $(shell $(PKG_CONFIG) --cflags glib-2.0 2>/dev/null)
GTK_LIBS := $(shell $(PKG_CONFIG) --libs gtk+-3.0 2>/dev/null)
CAIRO_CFLAGS := $(shell $(PKG_CONFIG) --cflags cairo 2>/dev/null)
CAIRO_LIBS := $(shell $(PKG_CONFIG) --libs cairo 2>/dev/null)
GLIB_LIBS := $(shell $(PKG_CONFIG) --libs glib-2.0 2>/dev/null)

CFLAGS ?= -O2 -g
CFLAGS += -std=c11 -Wall -Wextra -Wpedantic -Iinclude
SANITIZER_FLAGS := -fsanitize=address,undefined -fno-omit-frame-pointer
LDFLAGS ?=
BUILD := build
MODULE := $(BUILD)/native/metrics.so

# --- C test suites, generated from tests/MANIFEST ---------------------------
#
# One manifest feeds this Makefile, build.lua, and CMakeLists.txt, so a suite
# cannot be added to one build system and forgotten in another. The rules are
# generated by tools/tests-manifest.awk into build/tests.mk, which is included
# below; make rebuilds and re-reads it when the manifest changes.

TEST_MANIFEST := tests/MANIFEST
TEST_MAKE := $(BUILD)/tests.mk
TEST_HEADERS := $(wildcard include/*.h) tests/stubs/webview/webview.h
SANITIZER_FLAGS := -fsanitize=address,undefined -fno-omit-frame-pointer

$(TEST_MAKE): $(TEST_MANIFEST) tools/tests-manifest.awk Makefile
	@mkdir -p $(dir $@)
	awk -f tools/tests-manifest.awk $(TEST_MANIFEST) > $@

include $(TEST_MAKE)

.PHONY: all run test c-tests sanitized-test lua-test smoke-unit-test smoke-test
.PHONY: desktop clean check-lua check-gtk check-pdftotext check-cairo

all: $(MODULE)

check-lua:
	@command -v "$(LUA)" >/dev/null 2>&1 || { echo "Lua executable '$(LUA)' not found. Set LUA=... ."; exit 1; }
	@test -n "$(LUA_LIBS)" || { echo "Lua development files not found for pkg-config package '$(LUA_PKG)'. Install the Lua development package or set LUA_PKG=... ."; exit 1; }

check-cairo:
	@command -v $(PKG_CONFIG) >/dev/null 2>&1 || { echo "pkg-config not found."; exit 1; }
	@$(PKG_CONFIG) --exists cairo || { echo "cairo not found by pkg-config. The combined-outline PDF renderer needs it."; exit 1; }

check-gtk:
	@test -n "$(GTK_LIBS)" || { echo "GTK 3 development files not found for pkg-config 'gtk+-3.0'. Install the GTK 3 development package."; exit 1; }

check-pdftotext:
	@command -v pdftotext >/dev/null 2>&1 || { echo "pdftotext not found on PATH. Install Poppler (the TOC extraction tests spawn it)."; exit 1; }

$(MODULE): src/metrics.c src/lua_metrics.c include/metrics.h | check-lua
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(LUA_CFLAGS) -fPIC -shared -o $@ src/metrics.c src/lua_metrics.c $(LUA_LIBS) $(LDFLAGS)

# Builds every suite without running any of them.
c-tests: $(SUITE_BINS)

run: $(MODULE)
	LUA_PATH='./lua/?.lua;./lua/?/init.lua;;' LUA_CPATH='./build/?.so;;' $(LUA) lua/examples/demo.lua

lua-test: $(MODULE)
	LUA_PATH='./lua/?.lua;./lua/?/init.lua;;' LUA_CPATH='./build/?.so;;' $(LUA) tests/test_core.lua

# Every C suite in manifest order, then the Lua binding test.
test: check-gtk $(SUITE_TARGETS) lua-test

# The same suites under ASan/UBSan, generated from the same manifest.
sanitized-test: $(SUITE_SANITIZED)

# Real GUI smoke run: needs a graphical session, builds the frontend and the
# desktop host, then drives both render modes. See scripts/smoke.sh.
smoke-test:
	./scripts/smoke.sh

# Downloads the pinned WebView dependency through CMake on first use.
desktop:
	cmake -S . -B $(BUILD)/desktop
	cmake --build $(BUILD)/desktop --target metrics_desktop
	./$(BUILD)/desktop/bin/metrics_desktop

clean:
	rm -rf $(BUILD)
