local metrics = require("native.core")
local engine = metrics.from({ 1, 3, 5 })
local summary = engine:summary()

assert(summary.count == 3)
assert(summary.sum == 9)
assert(summary.mean == 3)
assert(summary.min == 1 and summary.max == 5)
assert(summary.variance == 8 / 3)
assert(engine:add(-1) == engine)
summary = engine:summary()
assert(summary.count == 4 and summary.min == -1)
assert(not pcall(function() engine:add(0 / 0) end))
assert(not pcall(function() engine:add(math.huge) end))
engine:reset()
assert(not pcall(function() engine:summary() end))

local singleton = metrics.from({ -42 })
summary = singleton:summary()
assert(summary.count == 1)
assert(summary.mean == -42 and summary.min == -42 and summary.max == -42)
assert(summary.variance == 0)
print("Lua integration tests passed")
