#ifndef SMOKE_H
#define SMOKE_H

/*
 * Smoke-run plumbing behind the smokeVerdict binding (layer 4: composition).
 *
 * A smoke run proves the real frontend-to-C path: METRICS_SMOKE=1 makes the
 * host inject a marker into the page, bind smokeVerdict, and turn the
 * frontend's verdict into the process exit code. The frontend owns the checks
 * (it has the real DOM and the real bridge); this module only reports, prints
 * one machine-readable line, and closes the window.
 *
 * The durable workspace is only written when the run is isolated, which
 * smoke_writable() detects from an explicit XDG_DATA_HOME, so a smoke run can
 * never overwrite a developer's real workspace.
 */

#include "app_support.h"

/* Returns 1 when METRICS_SMOKE requests a smoke run, 0 otherwise. */
int smoke_enabled(void);

/*
 * Returns 1 when the run may write the durable workspace (XDG_DATA_HOME is set
 * explicitly, as scripts/smoke.sh does with a temporary directory), 0 when the
 * smoke run must stay read-only.
 */
int smoke_writable(void);

/*
 * Returns the init-script fragment that flags the page as a smoke run, or NULL
 * when smoke mode is off. It sets window.__METRICS_SMOKE__ (and
 * window.__METRICS_SMOKE_WRITABLE__ when the run may persist) before any page
 * script runs. The returned string is a shared static literal.
 */
const char *smoke_init_script(void);

/*
 * Decodes a smokeVerdict request ["1"|"0", "report"].
 *
 * Decoding is deliberately strict: no escape sequences, no control characters,
 * and nothing after the closing bracket. The report is generated by
 * frontend-vue/src/smoke.js, so a backslash in it means the contract is broken,
 * not that it needs unescaping.
 *
 * Returns 1 on success and sets *pass and *report (caller frees *report).
 * Returns 0 on any malformed or NULL request, leaving *report NULL.
 */
int smoke_decode_verdict(const char *request, int *pass, char **report);

/*
 * Binds "smokeVerdict": prints the verdict, records the exit code, acks the
 * call, and terminates the event loop so the smoke run ends by itself.
 */
void on_smoke_verdict(const char *id, const char *request, void *argument);

#endif /* SMOKE_H */
